// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciqdciyrxzaqxaukoamn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcWRjaXlyeHphcXhhdWtvYW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNTM2NTIsImV4cCI6MjA4NjgyOTY1Mn0.hIUTQB1sbuTIV5CZ2QKhw0h1Neo0EK39pes4V9ZMB6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});